package com.test.invoke;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * AccountManagerService service = new AccountManagerService();
 * AccountManagerDelegate portType = service.getUpdateAppAcctSoap();
 * portType.updateAppAcctSoap(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "AccountManagerService", targetNamespace = "UpdateAppAcctSoap", wsdlLocation = "http://172.31.184.75:8080/all/UpdateAppAcctSoap?wsdl")
public class AccountManagerService extends Service {

	private final static URL ACCOUNTMANAGERSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.test.invoke.AccountManagerService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.test.invoke.AccountManagerService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://172.31.184.75:8080/all/UpdateAppAcctSoap?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://172.31.184.75:8080/all/UpdateAppAcctSoap?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ACCOUNTMANAGERSERVICE_WSDL_LOCATION = url;
	}

	public AccountManagerService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public AccountManagerService() {
		super(ACCOUNTMANAGERSERVICE_WSDL_LOCATION, new QName(
				"UpdateAppAcctSoap", "AccountManagerService"));
	}

	/**
	 * 
	 * @return returns AccountManagerDelegate
	 */
	@WebEndpoint(name = "UpdateAppAcctSoap")
	public AccountManagerDelegate getUpdateAppAcctSoap() {
		return super.getPort(
				new QName("UpdateAppAcctSoap", "UpdateAppAcctSoap"),
				AccountManagerDelegate.class);
	}

}
